[tools]
node = "24"
emsdk = "latest"
cmake = "latest"
ninja = "latest"

[tasks.install]
run = "npm install"
sources = [
  "package-lock.json"
]
outputs = { auto = true }

[tasks.pack]
description = "Pack the distribution from upstream repository"
run = """
[ "{{option(name="tag")}}" = "false" ] && echo "No tag provided" >&2 && exit 1
npm run -w packages/packer pack {{option(name="tag")}} {{option(name="game", default="poe2")}} clone
"""

[tasks.sync]
description = "Sync the packed distribution to Cloudflare R2"
run = """npm run -w packages/packer sync {{option(name="tag")}} {{option(name="game", default="poe2")}}"""


[tasks."driver:dev"]
description = "Start dev server for driver"
run = """
export RUN_GAME={{option(name="game", default="poe2")}}
export RUN_VERSION={{option(name="version", default="v0.8.0")}}
export RUN_BUILD={{option(name="build", default="release")}}
npm run -w packages/driver dev
"""

[tasks."driver:build"]
description = "Build driver"
run = "npm run -w packages/driver build"
