[tools]
sops = "latest"
aws-cli = "latest"

[env]
_.file = ".env.pob-cool.yaml"

[tasks.r2]
description = "aws s3 wrapper for Cloudflare R2"
run = "aws s3 --endpoint-url=https://621480c42e70995622a2d0a86bb7751c.r2.cloudflarestorage.com"
