name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: npm

      - uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: .emsdk-cache
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build -ws

      - name: Deploy
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm run deploy -w packages/web
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
