name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: npm

      - uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: .emsdk-cache
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build -ws

      - name: "Pack last version"
        run: npm run pack -w packages/packer v0.5.1 lastepoch clone

      - name: "Assemble"
        run: |
          cp -r packages/web/build/client dist
          mkdir dist/assets/versions;
          cp packages/packer/build/1/v0.5.1/r2 dist/assets/versions/v0.5.1 -r;
          cp version.json dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
  deploy:
    # Add a dependency to the build job
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: false

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
