name: Check for new releases
on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      game:
        description: Game to check for new releases (poe1 or poe2)
        type: choice
        required: true
        default: 'poe1'
        options:
          - poe1
          - poe2
      dry_run:
        description: 'Perform a dry run without making any changes'
        required: false
        default: 'true'

jobs:
  check-release:
    runs-on: ubuntu-latest
    env:
        VERSION_FILE: "version.json"
        GAME: "${{ github.event.inputs.game || 'poe1' }}"
        UPDATE_HEAD: "true"
        DRY_RUN: "${{ github.event.inputs.dry_run || 'false' }}"
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Get latest releases
        id: get_releases
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GAME === 'poe1' ? ['PathOfBuildingCommunity', 'PathOfBuilding'] : (process.env.GAME === 'poe2' ? ['PathOfBuildingCommunity', 'PathOfBuilding-PoE2'] : [undefined, undefined]);
            if (!owner || !repo) {
              throw new Error('Invalid game specified. Please use "poe1" or "poe2".');
            }

            const tags = await github.rest.repos.listTags({
              owner,
              repo,
              per_page: 10,
            });
            const tagsWithCommit = [];
            for (const tag of tags.data) {
              const commit = await github.rest.git.getCommit({
                owner,
                repo,
                commit_sha: tag.commit.sha,
              });
              tagsWithCommit.push({
                ...tag,
                commit: commit.data,
              });
            }
            core.info(`Latest tags: ${JSON.stringify(tagsWithCommit, null, 2)}`);
            return tagsWithCommit;

      - name: Determine new versions
        id: new_versions
        env:
          LATEST_TAGS: ${{ steps.get_releases.outputs.result }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const latestTags = JSON.parse(process.env.LATEST_TAGS);

            const versions = JSON.parse(fs.readFileSync(process.env.VERSION_FILE, 'utf8'));
            const knownVersions = versions[process.env.GAME].versions;

            const newTags = latestTags.filter(tag => !knownVersions.some(known => known.value === tag.name));
            core.info(`New tags: ${JSON.stringify(newTags, null, 2)}`);
            return newTags.length > 0 ? newTags : null;

      - name: Install dependencies
        if: steps.new_versions.outputs.result != 'null'
        run: npm ci

      - name: Pack and sync new versions
        if: steps.new_versions.outputs.result != 'null'
        env:
          NEW_TAGS: ${{ steps.new_versions.outputs.result }}
          R2_ENDPOINT_URL: https://621480c42e70995622a2d0a86bb7751c.r2.cloudflarestorage.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: actions/github-script@v7
        with:
          script: |
            const newTags = JSON.parse(process.env.NEW_TAGS);
            for (const tag of newTags) {
              exec.exec(`npm run -w packages/packer pack ${tag.name} ${process.env.GAME} clone`);
              if (process.env.DRY_RUN !== 'true') {
                exec.exec(`npm run -w packages/packer sync ${tag.name} ${process.env.GAME}`);
              }
            }

      - name: Update version.json
        if: steps.new_versions.outputs.result != 'null'
        env:
          NEW_TAGS: ${{ steps.new_versions.outputs.result }}
          R2_ENDPOINT_URL: https://621480c42e70995622a2d0a86bb7751c.r2.cloudflarestorage.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const newTags = JSON.parse(process.env.NEW_TAGS);
            const versions = JSON.parse(fs.readFileSync(process.env.VERSION_FILE, 'utf8'));

            versions[process.env.GAME].versions = [
              ...newTags.map(tag => ({ value: tag.name, date: tag.commit.committer.date })),
              ...versions[process.env.GAME].versions,
            ];

            if (process.env.UPDATE_HEAD === 'true') {
              versions[process.env.GAME].head = newTags[0].name;
            }

            core.info(`Updated versions: ${JSON.stringify(versions, null, 2)}`);
            fs.writeFileSync(process.env.VERSION_FILE, JSON.stringify(versions, null, 2));

            if (process.env.DRY_RUN !== 'true') {
              exec.exec(`aws s3 cp --region auto --endpoint-url ${process.env.R2_ENDPOINT_URL} version.json s3://pob-web/version.json`);
            }

      - name: Commit changes
        if: steps.new_versions.outputs.result != 'null' && env.DRY_RUN != 'true'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "atty303-bot[bot]"
          git config user.email "atty303-bot[bot]@users.noreply.github.com"
          git add $VERSION_FILE
          git commit -m "Update version.json with new releases (update head: $UPDATE_HEAD)"
          git push
